package com.usmandiscountstore.app.util

import android.content.Context
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

object Lang {

    const val EN = "en"
    const val UR = "ur"
    const val PA = "pa"

    private const val PREFS = "uds_lang"
    private const val KEY = "current_lang"

    var current: String by mutableStateOf(EN)
        private set

    fun load(context: Context) {
        val p = context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
        current = p.getString(KEY, EN) ?: EN
    }

    fun set(context: Context, lang: String) {
        current = lang
        context.getSharedPreferences(PREFS, Context.MODE_PRIVATE)
            .edit().putString(KEY, lang).apply()
    }

    fun displayName(lang: String): String = when (lang) {
        EN -> "English"
        UR -> "Roman Urdu"
        PA -> "پنجابی"
        else -> "English"
    }

    fun t(key: String): String = when (current) {
        UR -> ur[key] ?: en[key] ?: key
        PA -> pa[key] ?: en[key] ?: key
        else -> en[key] ?: key
    }

    // ========== ENGLISH ==========
    private val en = mapOf(
        // Common
        "app_name" to "Usman Discount Store",
        "app_address" to "Vehari Road, Old Hasilpur",
        "app_tagline" to "Staff Hazri & Khata Management",
        "yes" to "Yes", "no" to "No", "cancel" to "Cancel",
        "save" to "Save", "close" to "Close", "delete" to "Delete",
        "edit" to "Edit", "add" to "Add", "ok" to "OK",
        "loading" to "Loading...", "success" to "Success", "error" to "Error",
        "copyright" to "© 2026 Mr.DHooM 4K — All Rights Reserved",
        "back" to "Back",
        // Login
        "login_title" to "Login", "admin" to "Admin", "moderator" to "Moderator",
        "username" to "Username", "password" to "Password",
        "login_button" to "Login", "wrong_password" to "Wrong password",
        "username_empty" to "Please enter username",
        "hide" to "Hide", "show" to "Show",
        // Dashboard
        "welcome" to "Welcome",
        "admin_access" to "ADMIN ACCESS", "moderator_access" to "MODERATOR ACCESS",
        "geofence_active" to "Hasilpur Geofence Active",
        "geofence_sub" to "Vehari Road Counter • UDS-HSL-01",
        "store_modules" to "Store Modules",
        "mod_hazri" to "Mark Attendance", "mod_hazri_sub" to "GPS + face verify",
        "mod_staff_admin" to "Staff Management", "mod_staff_admin_sub" to "Add / edit / delete",
        "mod_staff_mod" to "Staff List", "mod_staff_mod_sub" to "View staff details",
        "mod_history" to "Attendance History", "mod_history_sub" to "Monthly report + edit",
        "mod_advance" to "Advance & Peshgi Khata", "mod_advance_sub" to "Loans and cash records",
        "mod_leave" to "Leave Requests", "mod_leave_pending" to "pending approval",
        "mod_leave_none" to "No pending requests",
        "mod_sheet" to "Salary Sheet (All Staff)", "mod_sheet_sub" to "Monthly + CSV export",
        "mod_slip" to "Salary Slips & Payroll", "mod_slip_sub" to "PDF slip per staff",
        "mod_settings" to "Admin Settings", "mod_settings_sub" to "Store + security",
        "logout" to "Logout", "language" to "Language", "select_language" to "Select Language",
        // Staff List
        "staff_record" to "Staff Record", "active_staff" to "active staff",
        "no_staff" to "No staff yet", "tap_to_add" to "Tap + below to add",
        "new_staff" to "New Staff", "staff_name" to "Name *", "mobile_number" to "Mobile Number",
        "designation" to "Designation", "daily_wage" to "Daily Wage (Rs.)",
        "role" to "Role", "staff" to "Staff",
        "face_registered" to "Face registered", "face_required" to "Face is required",
        "face_capture" to "Face Capture", "change_face" to "Change Face",
        "remove_staff" to "Remove Staff?", "remove_staff_msg" to "Remove this staff?",
        "add_staff" to "Add Staff", "edit_staff" to "Edit Staff",
        "processing_face" to "Processing face...",
        "face_error" to "Face embedding failed",
        "wage_label" to "Wage",
        // Attendance
        "hazri" to "Attendance", "present" to "Present", "half_day" to "Half Day",
        "leave" to "Leave", "absent" to "Absent", "not_marked" to "Not Marked",
        "all_present" to "All Present", "confirm_all_present" to "Mark All Present?",
        "confirm_all_msg" to "Mark all unmarked staff as Present today?",
        "marked_count" to "staff marked Present",
        "no_staff_attendance" to "No staff. Add staff first.",
        "gps_error" to "Cannot get location. Enable GPS.",
        "perm_error" to "Location permission required",
        "face_verify" to "Face Verify", "face_match_fail" to "Face did not match",
        // History
        "history" to "Attendance History", "monthly_report" to "Monthly report",
        "select_staff" to "Select staff", "month" to "Month",
        "monthly_summary" to "MONTHLY SUMMARY", "daily_records" to "DAILY RECORDS",
        "no_records" to "No records this month", "change_status" to "Change Status",
        "current_status" to "Current", "new_status" to "New Status",
        // Advance
        "advance_khata" to "Advance & Peshgi Khata", "total_advance" to "Total Advance",
        "salary_deduct" to "Will be deducted from salary",
        "no_advance" to "No advance records", "new_advance" to "New Advance",
        "amount" to "Amount (Rs.)", "reason" to "Reason", "payment_mode" to "Payment Mode",
        "cash" to "Cash", "easypaisa" to "Easypaisa", "ration" to "Ration",
        "select_staff_advance" to "Select staff",
        // Salary Sheet
        "salary_sheet" to "Salary Sheet", "all_staff_salary" to "All staff monthly salary",
        "total_payroll" to "TOTAL PAYROLL", "staff_wise" to "STAFF WISE",
        "gross" to "Gross", "bonus" to "Bonus", "advance" to "Advance",
        "net_payable" to "Net Payable", "add_bonus" to "Add Bonus",
        "overtime" to "Overtime", "eid_bonus" to "Eid Bonus",
        "festival_bonus" to "Festival Bonus", "performance" to "Performance", "other" to "Other",
        "present_x_wage" to "Present × Wage", "half_x_wage" to "Half × Wage/2",
        "export_csv" to "Export CSV", "csv_ready" to "CSV ready — share it",
        // Leave
        "leave_requests" to "Leave Requests", "pending" to "Pending",
        "approved" to "Approved", "rejected" to "Rejected",
        "all_caught_up" to "All caught up",
        "no_pending_leave" to "No pending requests",
        "no_approved_leave" to "No approved requests",
        "no_rejected_leave" to "No rejected requests",
        "from_date" to "From Date (yyyy-MM-dd)", "to_date" to "To Date (yyyy-MM-dd)",
        "approve" to "Approve", "reject" to "Reject",
        "requested" to "Requested", "reviewed_by" to "Reviewed by",
        "leave_approved" to "Leave Approved", "leave_rejected" to "Leave Rejected",
        "new_leave_request" to "New Leave Request", "submit" to "Submit",
        "days_leave_marked" to "days marked as Leave",
        // Admin Settings
        "admin_settings" to "Admin Settings", "store_security" to "Store + Security",
        "store_info" to "Store Information", "store_name" to "Store Name",
        "address" to "Address", "geofence_location" to "Geofence Location",
        "latitude" to "Latitude", "longitude" to "Longitude",
        "radius_meters" to "Radius (meters)",
        "radius_hint" to "Attendance allowed within this radius",
        "pick_location" to "Pick Store Location from Map",
        "whatsapp_alerts" to "WhatsApp Alerts", "admin_whatsapp" to "Admin WhatsApp",
        "whatsapp_format" to "92XXXXXXXXXX format",
        "attendance_alerts" to "Attendance Alerts",
        "alert_hint" to "Send WhatsApp alert on every check-in",
        "security" to "Security", "admin_password" to "Admin Password",
        "moderator_password" to "Moderator Password",
        "update_passwords" to "Update Passwords",
        "save_settings" to "Save Store Settings",
        "pwd_too_short" to "Password must be at least 4 characters",
        "pwd_updated" to "Passwords updated",
        "settings_saved" to "Store settings saved",
        // Map
        "store_location" to "Store Location", "tap_map_hint" to "Tap on map to set pin",
        "selected_location" to "SELECTED LOCATION", "fetching_address" to "Fetching address...",
        "set_this_location" to "Set This Location",
        "tap_map_bottom" to "Tap anywhere on the map to place the pin",
        // Salary Slip
        "salary_slip" to "Salary Slip", "pdf_print" to "PDF generate + print",
        "salary_breakdown" to "SALARY BREAKDOWN",
        "save_pdf" to "Save PDF", "share" to "Share", "print_open" to "Print / Open PDF"
    )

    // ========== ROMAN URDU ==========
    private val ur = mapOf(
        "app_name" to "Usman Discount Store", "app_address" to "Vehari Road, Old Hasilpur",
        "app_tagline" to "Staff Hazri aur Khata Management",
        "yes" to "Haan", "no" to "Nahi", "cancel" to "Cancel",
        "save" to "Save", "close" to "Close", "delete" to "Delete",
        "edit" to "Edit", "add" to "Add", "ok" to "Theek",
        "loading" to "Intezaar karein...", "success" to "Kamyabi", "error" to "Masla",
        "copyright" to "© 2026 Mr.DHooM 4K — Tamam Haqooq Mehfooz",
        "back" to "Wapas",
        "login_title" to "Login", "admin" to "Admin", "moderator" to "Moderator",
        "username" to "Username", "password" to "Password",
        "login_button" to "Login Karein", "wrong_password" to "Ghalat password",
        "username_empty" to "Username darj karein",
        "hide" to "Chupayein", "show" to "Dekhein",
        "welcome" to "Khush Amdeed",
        "admin_access" to "ADMIN ACCESS", "moderator_access" to "MODERATOR ACCESS",
        "geofence_active" to "Hasilpur Geofence Active",
        "geofence_sub" to "Vehari Road Counter • UDS-HSL-01",
        "store_modules" to "Store Ke Kaam",
        "mod_hazri" to "Hazri Lagao", "mod_hazri_sub" to "GPS aur face verify",
        "mod_staff_admin" to "Mulazimeen Management", "mod_staff_admin_sub" to "Staff add / edit / delete",
        "mod_staff_mod" to "Mulazimeen List", "mod_staff_mod_sub" to "Staff ki tafseelat",
        "mod_history" to "Hazri History", "mod_history_sub" to "Mahine ki report aur edit",
        "mod_advance" to "Advance aur Peshgi Khata", "mod_advance_sub" to "Udhaar aur cash ka record",
        "mod_leave" to "Chutti Ki Requests", "mod_leave_pending" to "manzoori ka intezaar",
        "mod_leave_none" to "Koi pending request nahi",
        "mod_sheet" to "Salary Sheet (Sab Staff)", "mod_sheet_sub" to "Mahine ki tankhwah aur CSV",
        "mod_slip" to "Salary Slips aur Payroll", "mod_slip_sub" to "Har staff ki PDF slip",
        "mod_settings" to "Admin Settings", "mod_settings_sub" to "Store aur security",
        "logout" to "Logout", "language" to "Zubaan", "select_language" to "Zubaan Chuno",
        "staff_record" to "Mulazimeen Record", "active_staff" to "active staff",
        "no_staff" to "Koi staff nahi", "tap_to_add" to "Neeche + dabao",
        "new_staff" to "Naya Staff", "staff_name" to "Naam *", "mobile_number" to "Mobile Number",
        "designation" to "Designation", "daily_wage" to "Daily Wage (Rs.)",
        "role" to "Role", "staff" to "Staff",
        "face_registered" to "Face registered", "face_required" to "Face zaroori hai",
        "face_capture" to "Face Capture", "change_face" to "Face Change",
        "remove_staff" to "Staff Remove Karein?", "remove_staff_msg" to "Is staff ko remove karein?",
        "add_staff" to "Naya Staff Add", "edit_staff" to "Staff Edit",
        "processing_face" to "Face process ho raha hai...",
        "face_error" to "Face embedding nahi hua",
        "wage_label" to "Ujrat",
        "hazri" to "Hazri", "present" to "Hazir", "half_day" to "Half Day",
        "leave" to "Chutti", "absent" to "Gair", "not_marked" to "Nahi Lagi",
        "all_present" to "Sab Hazir", "confirm_all_present" to "Sab Hazir Mark Karein?",
        "confirm_all_msg" to "Aaj ke saare unmarked staff ko Hazir mark karna hai?",
        "marked_count" to "staff Hazir mark kiye",
        "no_staff_attendance" to "Koi staff nahi. Pehle staff add karo.",
        "gps_error" to "Location nahi mil rahi. GPS on karo.",
        "perm_error" to "Location permission chahiye",
        "face_verify" to "Face Verify", "face_match_fail" to "Face match nahi hua",
        "history" to "Hazri History", "monthly_report" to "Mahine ki report",
        "select_staff" to "Staff select karo", "month" to "Mahina",
        "monthly_summary" to "MAHINE KA KHULASA", "daily_records" to "ROZANA RECORDS",
        "no_records" to "Is mahine koi record nahi", "change_status" to "Status Change Karein",
        "current_status" to "Abhi", "new_status" to "Naya Status",
        "advance_khata" to "Advance aur Peshgi Khata", "total_advance" to "Kul Advance",
        "salary_deduct" to "Salary se kat jayega",
        "no_advance" to "Koi advance record nahi", "new_advance" to "Nayi Peshgi",
        "amount" to "Raqam (Rs.)", "reason" to "Wajah", "payment_mode" to "Payment Tareeqa",
        "cash" to "Cash", "easypaisa" to "Easypaisa", "ration" to "Ration",
        "select_staff_advance" to "Staff select karo",
        "salary_sheet" to "Salary Sheet", "all_staff_salary" to "Sab staff ki mahine ki tankhwah",
        "total_payroll" to "KUL PAYROLL", "staff_wise" to "STAFF WISE",
        "gross" to "Gross", "bonus" to "Bonus", "advance" to "Advance",
        "net_payable" to "Net Payable", "add_bonus" to "Bonus Add",
        "overtime" to "Overtime", "eid_bonus" to "Eid Bonus",
        "festival_bonus" to "Festival Bonus", "performance" to "Performance", "other" to "Aur",
        "present_x_wage" to "Hazir × Ujrat", "half_x_wage" to "Half × Ujrat/2",
        "export_csv" to "CSV Export", "csv_ready" to "CSV tayyar — share karo",
        "leave_requests" to "Chutti Ki Requests", "pending" to "Pending",
        "approved" to "Manzoor", "rejected" to "Reject",
        "all_caught_up" to "Sab theek hai",
        "no_pending_leave" to "Koi pending request nahi",
        "no_approved_leave" to "Koi approved request nahi",
        "no_rejected_leave" to "Koi rejected request nahi",
        "from_date" to "Se Date (yyyy-MM-dd)", "to_date" to "Tak Date (yyyy-MM-dd)",
        "approve" to "Manzoor", "reject" to "Reject",
        "requested" to "Bheji", "reviewed_by" to "Review kiya",
        "leave_approved" to "Chutti Manzoor", "leave_rejected" to "Chutti Reject",
        "new_leave_request" to "Nayi Chutti Request", "submit" to "Bhejo",
        "days_leave_marked" to "din Chutti mark ki gayi",
        "admin_settings" to "Admin Settings", "store_security" to "Store aur Security",
        "store_info" to "Store Ki Maloomat", "store_name" to "Store ka Naam",
        "address" to "Pata", "geofence_location" to "Geofence Location",
        "latitude" to "Latitude", "longitude" to "Longitude",
        "radius_meters" to "Radius (meters)",
        "radius_hint" to "Is radius ke andar hazri lagegi",
        "pick_location" to "Map se Store Location Chuno",
        "whatsapp_alerts" to "WhatsApp Alerts", "admin_whatsapp" to "Admin WhatsApp",
        "whatsapp_format" to "92XXXXXXXXXX format",
        "attendance_alerts" to "Hazri Alerts",
        "alert_hint" to "Har hazri pe WhatsApp alert bhejo",
        "security" to "Security", "admin_password" to "Admin Password",
        "moderator_password" to "Moderator Password",
        "update_passwords" to "Passwords Update",
        "save_settings" to "Store Settings Save",
        "pwd_too_short" to "Password kam az kam 4 character",
        "pwd_updated" to "Passwords update ho gaye",
        "settings_saved" to "Store settings save ho gayin",
        "store_location" to "Store Location", "tap_map_hint" to "Map pe tap karke pin lagao",
        "selected_location" to "CHUNI HUI LOCATION", "fetching_address" to "Address dhoond raha hai...",
        "set_this_location" to "Ye Location Set Karo",
        "tap_map_bottom" to "Map pe kahin bhi tap karo pin lagane ke liye",
        "salary_slip" to "Salary Slip", "pdf_print" to "PDF banao aur print karo",
        "salary_breakdown" to "SALARY BREAKDOWN",
        "save_pdf" to "PDF Save", "share" to "Share", "print_open" to "Print / PDF Kholo"
    )

    // ========== PUNJABI ==========
    private val pa = mapOf(
        "app_name" to "عثمان ڈسکاؤنٹ سٹور", "app_address" to "وہاڑی روڈ، پرانا حاصل پور",
        "app_tagline" to "عملے دی حاضری تے کھاتہ",
        "yes" to "ہاں", "no" to "نہیں", "cancel" to "منسوخ",
        "save" to "محفوظ", "close" to "بند", "delete" to "مٹاؤ",
        "edit" to "تبدیل", "add" to "شامل", "ok" to "ٹھیک",
        "loading" to "اڈیک کرو...", "success" to "کامیابی", "error" to "مسئلہ",
        "copyright" to "© 2026 Mr.DHooM 4K — سارے حق محفوظ",
        "back" to "واپس",
        "login_title" to "لاگ ان", "admin" to "ایڈمن", "moderator" to "موڈریٹر",
        "username" to "صارف دا ناں", "password" to "پاس ورڈ",
        "login_button" to "لاگ ان کرو", "wrong_password" to "غلط پاس ورڈ",
        "username_empty" to "صارف دا ناں لکھو",
        "hide" to "لکاؤ", "show" to "دکھاؤ",
        "welcome" to "جی آیاں نوں",
        "admin_access" to "ایڈمن رسائی", "moderator_access" to "موڈریٹر رسائی",
        "geofence_active" to "حاصل پور جیو فینس چالو",
        "geofence_sub" to "وہاڑی روڈ کاؤنٹر • UDS-HSL-01",
        "store_modules" to "سٹور دے کم",
        "mod_hazri" to "حاضری لاؤ", "mod_hazri_sub" to "جی پی ایس تے چہرہ تصدیق",
        "mod_staff_admin" to "عملے دا انتظام", "mod_staff_admin_sub" to "شامل / تبدیل / مٹاؤ",
        "mod_staff_mod" to "عملے دی لسٹ", "mod_staff_mod_sub" to "عملے دی تفصیل ویکھو",
        "mod_history" to "حاضری دی تریخ", "mod_history_sub" to "مہینے دی رپورٹ تے تبدیلی",
        "mod_advance" to "ایڈوانس تے پیسگی کھاتہ", "mod_advance_sub" to "قرضہ تے نقد دا ریکارڈ",
        "mod_leave" to "چھٹی دی درخواست", "mod_leave_pending" to "منظوری دی اڈیک",
        "mod_leave_none" to "کوئی درخواست نہیں",
        "mod_sheet" to "تنخواہ شیٹ (سارا عملہ)", "mod_sheet_sub" to "مہینے دی تنخواہ تے CSV",
        "mod_slip" to "تنخواہ سلپ تے پے رول", "mod_slip_sub" to "ہر بندے دی PDF سلپ",
        "mod_settings" to "ایڈمن ترتیبات", "mod_settings_sub" to "سٹور تے سیکیورٹی",
        "logout" to "باہر نکلو", "language" to "بولی", "select_language" to "بولی چنو",
        "staff_record" to "عملے دا ریکارڈ", "active_staff" to "چالو عملہ",
        "no_staff" to "کوئی عملہ نہیں", "tap_to_add" to "تھلے + دباؤ",
        "new_staff" to "نواں بندہ", "staff_name" to "ناں *", "mobile_number" to "موبائل نمبر",
        "designation" to "عہدہ", "daily_wage" to "روزانہ اجرت (روپے)",
        "role" to "کردار", "staff" to "عملہ",
        "face_registered" to "چہرہ رجسٹرڈ", "face_required" to "چہرہ ضروری اے",
        "face_capture" to "چہرہ پھڑو", "change_face" to "چہرہ تبدیل",
        "remove_staff" to "بندہ مٹاؤ؟", "remove_staff_msg" to "ایس بندے نوں مٹانا اے؟",
        "add_staff" to "نواں بندہ شامل", "edit_staff" to "بندہ تبدیل",
        "processing_face" to "چہرہ پروسیس ہو رہیا اے...",
        "face_error" to "چہرہ ایمبیڈنگ نہ ہوئی",
        "wage_label" to "اجرت",
        "hazri" to "حاضری", "present" to "حاضر", "half_day" to "ادھا دن",
        "leave" to "چھٹی", "absent" to "غیر حاضر", "not_marked" to "نہیں لگی",
        "all_present" to "سارے حاضر", "confirm_all_present" to "سارے حاضر کرو؟",
        "confirm_all_msg" to "اج دے سارے بغیر نشان والے بندے حاضر کرنے نیں؟",
        "marked_count" to "بندے حاضر کیتے",
        "no_staff_attendance" to "کوئی عملہ نہیں۔ پہلے شامل کرو۔",
        "gps_error" to "لوکیشن نہیں لبھی۔ جی پی ایس چالو کرو۔",
        "perm_error" to "لوکیشن دی اجازت چاہیدی اے",
        "face_verify" to "چہرہ تصدیق", "face_match_fail" to "چہرہ نہیں ملیا",
        "history" to "حاضری دی تریخ", "monthly_report" to "مہینے دی رپورٹ",
        "select_staff" to "بندہ چنو", "month" to "مہینہ",
        "monthly_summary" to "مہینے دا خلاصہ", "daily_records" to "روزانہ ریکارڈ",
        "no_records" to "ایس مہینے کوئی ریکارڈ نہیں", "change_status" to "حالت بدلو",
        "current_status" to "ہن", "new_status" to "نویں حالت",
        "advance_khata" to "ایڈوانس تے پیسگی کھاتہ", "total_advance" to "کل ایڈوانس",
        "salary_deduct" to "تنخواہ وچوں کٹ جاوے گا",
        "no_advance" to "کوئی ایڈوانس ریکارڈ نہیں", "new_advance" to "نویں پیسگی",
        "amount" to "رقم (روپے)", "reason" to "وجہ", "payment_mode" to "ادائیگی دا طریقہ",
        "cash" to "نقد", "easypaisa" to "ایزی پیسہ", "ration" to "راشن",
        "select_staff_advance" to "بندہ چنو",
        "salary_sheet" to "تنخواہ شیٹ", "all_staff_salary" to "سارے عملے دی مہینے دی تنخواہ",
        "total_payroll" to "کل تنخواہ", "staff_wise" to "بندے مطابق",
        "gross" to "کل", "bonus" to "انعام", "advance" to "ایڈوانس",
        "net_payable" to "خالص تنخواہ", "add_bonus" to "انعام شامل",
        "overtime" to "اوور ٹائم", "eid_bonus" to "عید انعام",
        "festival_bonus" to "تہوار انعام", "performance" to "کارکردگی", "other" to "ہور",
        "present_x_wage" to "حاضر × اجرت", "half_x_wage" to "ادھا × اجرت/2",
        "export_csv" to "CSV ایکسپورٹ", "csv_ready" to "CSV تیار — شیئر کرو",
        "leave_requests" to "چھٹی دیاں درخواستاں", "pending" to "باقی",
        "approved" to "منظور", "rejected" to "مسترد",
        "all_caught_up" to "سب ٹھیک اے",
        "no_pending_leave" to "کوئی درخواست نہیں",
        "no_approved_leave" to "کوئی منظور درخواست نہیں",
        "no_rejected_leave" to "کوئی مسترد درخواست نہیں",
        "from_date" to "توں تاریخ (yyyy-MM-dd)", "to_date" to "تک تاریخ (yyyy-MM-dd)",
        "approve" to "منظور کرو", "reject" to "مسترد کرو",
        "requested" to "بھیجی", "reviewed_by" to "ویکھیا",
        "leave_approved" to "چھٹی منظور", "leave_rejected" to "چھٹی مسترد",
        "new_leave_request" to "نویں چھٹی درخواست", "submit" to "بھیجو",
        "days_leave_marked" to "دن چھٹی نشان لگی",
        "admin_settings" to "ایڈمن ترتیبات", "store_security" to "سٹور تے سیکیورٹی",
        "store_info" to "سٹور دی معلومات", "store_name" to "سٹور دا ناں",
        "address" to "پتہ", "geofence_location" to "جیو فینس تھاں",
        "latitude" to "لیٹیٹیوڈ", "longitude" to "لانگیٹیوڈ",
        "radius_meters" to "رداس (میٹر)",
        "radius_hint" to "ایس رداس دے اندر حاضری لگے گی",
        "pick_location" to "نقشے توں سٹور تھاں چنو",
        "whatsapp_alerts" to "واٹس ایپ الرٹ", "admin_whatsapp" to "ایڈمن واٹس ایپ",
        "whatsapp_format" to "92XXXXXXXXXX فارمیٹ",
        "attendance_alerts" to "حاضری الرٹ",
        "alert_hint" to "ہر حاضری تے واٹس ایپ الرٹ بھیجو",
        "security" to "سیکیورٹی", "admin_password" to "ایڈمن پاس ورڈ",
        "moderator_password" to "موڈریٹر پاس ورڈ",
        "update_passwords" to "پاس ورڈ بدلو",
        "save_settings" to "سٹور ترتیبات محفوظ",
        "pwd_too_short" to "پاس ورڈ گھٹو گھٹ 4 اکھر",
        "pwd_updated" to "پاس ورڈ بدل گئے",
        "settings_saved" to "سٹور ترتیبات محفوظ ہو گئیاں",
        "store_location" to "سٹور تھاں", "tap_map_hint" to "نقشے تے ٹیپ کر کے پن لاؤ",
        "selected_location" to "چنی ہوئی تھاں", "fetching_address" to "پتہ لبھ رہیا اے...",
        "set_this_location" to "ایہ تھاں سیٹ کرو",
        "tap_map_bottom" to "نقشے تے کتے وی ٹیپ کرو پن لان لئی",
        "salary_slip" to "تنخواہ سلپ", "pdf_print" to "PDF بناو تے پرنٹ کرو",
        "salary_breakdown" to "تنخواہ دی تفصیل",
        "save_pdf" to "PDF محفوظ", "share" to "شیئر", "print_open" to "پرنٹ / PDF کھولو"
    )
}
